[profile.default]
ffi = false
fuzz_runs = 256
libs = ["../../node_modules", "node_modules"]
optimizer = true
optimizer_runs = 1000000
out = "out"
solc = "0.8.28"
src = "src"
verbosity = 1
gas_reports = ["*"]
memory_limit = 43554432
